# Generated by Django 5.2.3 on 2026-04-20 15:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medication', '0002_alter_patient_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('water_intake_liter', models.FloatField(default=0)),
                ('steps_walked', models.IntegerField(default=0)),
                ('calories_consumed', models.IntegerField(default=0)),
                ('mood', models.CharField(blank=True, max_length=50, null=True)),
                ('progress_note', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DietaryRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.TextField()),
                ('lunch', models.TextField()),
                ('dinner', models.TextField()),
                ('snacks', models.TextField(blank=True, null=True)),
                ('food_to_avoid', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField()),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HealthPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_chart', models.TextField()),
                ('exercise_plan', models.TextField()),
                ('sleep_plan', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.patient')),
            ],
        ),
        migrations.CreateModel(
            name='healthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('height_feet', models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0.3)])),
                ('height_inches', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('disease', models.TextField()),
                ('addition_info', models.TextField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medication.patient')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
