# Generated by Django 5.2.3 on 2025-11-19 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medication', '0002_medicinescheduler_time_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('water_intake_liter', models.FloatField(default=0)),
                ('steps_walked', models.IntegerField(default=0)),
                ('calories_consumed', models.IntegerField(default=0)),
                ('mood', models.CharField(blank=True, max_length=50, null=True)),
                ('progress_note', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HealthPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_chart', models.TextField()),
                ('exercise_plan', models.TextField()),
                ('sleep_plan', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.patient')),
            ],
        ),
        migrations.CreateModel(
            name='healthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('disease', models.TextField()),
                ('addition_info', models.TextField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medication.patient')),
            ],
        ),
    ]
