# Generated by Django 5.2.3 on 2026-04-11 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('med_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('expire_date', models.DateField()),
                ('dosage', models.TextField()),
                ('instruction', models.TextField()),
                ('number_of_pills_in_day', models.IntegerField(default=1)),
                ('part_of_day', models.CharField(default='morning', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='time_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineScheduler',
            fields=[
                ('med_sch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('times_per_day', models.IntegerField()),
                ('med_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medication.medicine')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medication.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescrip_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prescrip_analogy', models.TextField()),
                ('medicine_info', models.ManyToManyField(blank=True, related_name='prescriptions', to='medication.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medication.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminder_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('sch_id', models.BigIntegerField()),
                ('reminder_time', models.DateField(default=django.utils.timezone.now)),
                ('is_taken', models.BooleanField(default=False)),
                ('med_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='medication.medicine')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='medication.patient')),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.TimeField()),
                ('scheduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.medicinescheduler')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.time_slot')),
            ],
        ),
        migrations.AddField(
            model_name='medicinescheduler',
            name='time_slots',
            field=models.ManyToManyField(related_name='schedules', through='medication.SchedulerTime', to='medication.time_slot'),
        ),
    ]
