# Generated by Django 5.2.3 on 2025-11-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinescheduler',
            name='time_slots',
            field=models.ManyToManyField(related_name='schedules', through='medication.SchedulerTime', to='medication.time_slot'),
        ),
    ]
